name: Preproduction

on:
  push:
    branches:
      - main

jobs:
  pre-deploy:
    runs-on: ubuntu-18.04
    # runs-on: ubuntu-latest
    steps:
      - name: Checkout to code
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm Install
      - name: Run lint
        run: npm run lint
      - name: Run tests
        run: npm run test