name: Preproduction

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  pre-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to code
        # uses: actions/checkout@v4
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 #4.2.1
      - name: Install node.js
        # uses: actions/setup-node@v4
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 #4.4.0
        with:
          node-version: '22.14.0'
      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint --if-present
      - name: Run tests
        run: npm run test --if-present
      - name: Build project
        if: ${{ github.event_name != 'pull_request' }}
        run: npm run build
      - name: Listar archivos
        run: ls -l